---
- name: Deploying spring boot application on linux server
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic/
    package_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    appuser: springbootuser
    #test_var: Id2
  tasks:
    - name: fail the execution if the distrubution is not ubuntu
      fail:
        msg: this is not an ubuntu machine
      when: ansible_facts['distribution'] != "Ubuntu"
    - name: Update ubuntu packages and inatalling java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      notify:
        - debug msg for java
    - name: Making directory 
      file: 
        path: "{{ app_dir }}"
        state: directory
      notify:
        - debug msg for created directory
    - name: Downloading the application to the path
      get_url:
        url: "{{ package_url }}"
        dest: "{{ app_file }}"
    - name: Adding user
      user:
        name: "{{ appuser }}"
        password: "{{ appuser }}"
      notify:
        - permissions for a file
    - name: copying service file to remote
      copy:
        src: springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: Enable and start springpetclinic service
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started
  handlers:
    - name: permissions for a file
      file: 
        owner: "{{ appuser }}"
        path: "{{ app_file }}"
        mode: '500'
        state: file
    - name: debug msg for java
      debug: 
        msg: java is succesfully installed
    - name: debug msg for created directory
      debug: 
        msg: app directory is created
    
      