---
- name: Deploying spring boot application on linux server
  hosts: appserver
  become: yes
  tasks:
    - name: Update ubuntu packages and inatalling java
      apt:
        name: openjdk-11-jdk 
        update_cache: yes
        state: present
    - name: Making directory 
      file: 
        path: /usr/share/springpetclinic/
        state: directory
    - name: Downloading the application to the path
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: Adding user
      user:
        name: springbootuser
        password: springbootuser
    - name: Adding permission to user
      file: 
        owner: springbootuser
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        mode: '500'
        state: file