---
- name: Deploying spring boot application on linux server
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic/
    package_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    appuser: springbootuser
    #test_var: Id2
  tasks:
    - name: debug java package name
      debug: 
        var: java_package
    - name: debug test_var name
      debug: 
        var: test_var
    - name: Update ubuntu packages and inatalling java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: Making directory 
      file: 
        path: "{{ app_dir }}"
        state: directory
    - name: Downloading the application to the path
      get_url:
        url: "{{ package_url }}"
        dest: "{{ app_file }}"
    - name: Adding user
      user:
        name: "{{ appuser }}"
        password: "{{ appuser }}"
    - name: Adding permission to user
      file: 
        owner: "{{ appuser }}"
        path: "{{ app_file }}"
        mode: '500'
        state: file
    - name: copying service file to remote
      copy:
        src: springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: Enable and start springpetclinic service
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started